language: node_js
node_js: "node"
cache:
  directories:
    - node_modules
before_install:
  - git clone --depth 1 https://github.com/sstephenson/bats.git
install:
  - npm install
script:
  - npm run test
